blank_issues_enabled: false
contact_links:
  - name: Community
    url: https://github.com/CodeforHawaii/discussions
    about: Start or join a conversation
  - name: Contact
    url: https://www.codeforhawaii.org
    about: Contact us 
