name: Run notebook file

on:
  push:
    branches:
    - AddingHZADataAction


jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
        id-token: 'write'
        actions: 'write'

    steps:
    - uses: 'actions/checkout@v3'

    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./data-pipeline/requirements.txt
        touch /home/runner/work/Hawaii-Zoning-Atlas/Hawaii-Zoning-Atlas/papermill-nb-runner.out
    - uses: yaananth/run-notebook@v2
      env:
        RUNNER: ${{ toJson(runner) }}
        SECRETS: ${{ toJson(secrets) }}
        GITHUB: ${{ toJson(github) }}
      with:
        notebook: "./data-pipeline/CombineJurisdictions.ipynb"
        isReport: False
        poll: False
    - name: Check output location
      run: |
        pwd
    - name: Commit final.geojson
      uses: EndBug/add-and-commit@v9
      with:
        message: 'Add the final.geojson'
        add: 'final.geojson --force'
        cwd: './data-pipeline/'
