name: Run notebook file

on:
  push:
    branches:
    - AddingHZADataAction


jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
        contents: 'read'
        id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'

    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./data-pipeline/requirements.txt
    - uses: yaananth/run-notebook@v2
      env:
        RUNNER: ${{ toJson(runner) }}
        SECRETS: ${{ toJson(secrets) }}
        GITHUB: ${{ toJson(github) }}
      with:
        notebook: "./data-pipeline/CombineJurisdictions.ipynb"
        isReport: False
        poll: True
    - name: Check output location
      run: ls -R
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: final.geojson
        path: ${{ RUNNER.temp }}/nb-runner/final.geojson
      env:
        RUNNER: ${{ toJson(runner) }}